FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /app/seed_binary ./cmd/seed

FROM gcr.io/distroless/base-debian12
WORKDIR /app

COPY --from=builder /app/seed_binary /app/seed_app

USER nonroot:nonroot

CMD ["/app/seed_app"]