services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    container_name: my_migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
      "up"
    ]
    env_file:
      - .env

  seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    container_name: seed
    depends_on:
      - db
      - migrate
    env_file:
      - .env

  app:
    build: .
    container_name: my_go_app
    restart: unless-stopped
    depends_on:
      - db
      - migrate
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata: