# Этап сборки
FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o seed-app ./cmd/seed

# Этап запуска
FROM alpine:3.19
WORKDIR /app

COPY --from=builder /app/seed-app .
COPY seed ./seed
COPY .env .env

CMD ["./seed-app"]