CREATE TABLE IF NOT EXISTS user_prizes (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    prize_id BIGINT NOT NULL REFERENCES prizes(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);